### ISSUE TITLE
Barrels are too powerful[BUG]

### ISSUE THREAD

**Issue by CynicalMod** [Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey#6]
I spawned, and within the given spawn region I managed to find a barrel with 5 diamonds, redstone blocks, and rails. While redstone blocks rails etc, aren't the greatest, finding 5 diamonds is pretty insane, especially for a common barrel. 

 I'm not entirely sure if this is a bug, or perhaps the chance was risen far too high, I would probably suggest lowering chance honestly.
 Sorry by the way for not screenshotting my initial time opening the barrel. 
 
 Also, I would love to see Farmers Delight be added, it really adds a lot of great things, such as wild carrots/onions, and complex foods.
 Thank you for your time and loving the mod selection so far! <3

**Comment by JustFoxx** [comment]
Oh, well loot of those barrels is like loot of burries chest, but i could change loot from them and one of mods idk why just make everything to be common

**Comment by JustFoxx** [comment]
and i will think about adding thag mod

**Comment by JustFoxx** [comment]
sorry but Farmers Delight is only for forge

**Comment by JustFoxx** [comment]
oh wait i found fabric port, nvm

**Comment by JustFoxx** [comment]
mod will be added in https://github.com/Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey/tree/a0.4.9

**Comment by JustFoxx** [comment]
https://github.com/Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey/releases/tag/a0.4.9
