### ISSUE TITLE
Fps Issue [BUG]

### ISSUE THREAD

**Issue by CynicalMod** [Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey#7]
I found if I were to hold something such as a; Lantern, torch, or anything that has a dynamic light source, it would drop frames I would say by 5-10% depending where you are. 

  I'm also using Complementary 1.18.1 shaders, with compatibility mode enabled for mods.

**Comment by JustFoxx** [comment]
Go to settings, and LambdaDynamicLights, and disable it or just make it less dynamic
