### ISSUE TITLE
Crash with mod; Effective, Fabric Lifecycle Events (v1) [BUG]

### ISSUE THREAD

**Issue by CynicalMod** [Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey#8]
Link to crash 1 https://crashy.net/uPjJBjlHUX3lD7UnfBjn

Link to crash 2 https://bytebin.lucko.me/7I5wxbiyll

**Comment by JustFoxx** [comment]
effective mod crashing, will be repaired in next release a04.9

**Comment by JustFoxx** [comment]
Issues will be repaired in

**Comment by JustFoxx** [comment]
https://github.com/Adventures-of-Fox/Adventures-Of-Fox-Beginning-Of-A-Journey/releases/tag/a0.4.9
